/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserRouteRouteImport } from './routes/user.route'
import { Route as ReaderRouteRouteImport } from './routes/reader.route'
import { Route as LoginRouteRouteImport } from './routes/login.route'
import { Route as FinesRouteRouteImport } from './routes/fines.route'
import { Route as CategoryRouteRouteImport } from './routes/category.route'
import { Route as Borrow_recordsRouteRouteImport } from './routes/borrow_records.route'
import { Route as BorrowRecordsRouteRouteImport } from './routes/borrow-records.route'
import { Route as BookRouteRouteImport } from './routes/book.route'
import { Route as AuthorRouteRouteImport } from './routes/author.route'
import { Route as AccountRouteRouteImport } from './routes/account.route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const UserRouteRoute = UserRouteRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderRouteRoute = ReaderRouteRouteImport.update({
  id: '/reader',
  path: '/reader',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinesRouteRoute = FinesRouteRouteImport.update({
  id: '/fines',
  path: '/fines',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRouteRoute = CategoryRouteRouteImport.update({
  id: '/category',
  path: '/category',
  getParentRoute: () => rootRouteImport,
} as any)
const Borrow_recordsRouteRoute = Borrow_recordsRouteRouteImport.update({
  id: '/borrow_records',
  path: '/borrow_records',
  getParentRoute: () => rootRouteImport,
} as any)
const BorrowRecordsRouteRoute = BorrowRecordsRouteRouteImport.update({
  id: '/borrow-records',
  path: '/borrow-records',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRouteRoute = BookRouteRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorRouteRoute = AuthorRouteRouteImport.update({
  id: '/author',
  path: '/author',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRoute
  '/author': typeof AuthorRouteRoute
  '/book': typeof BookRouteRoute
  '/borrow-records': typeof BorrowRecordsRouteRoute
  '/borrow_records': typeof Borrow_recordsRouteRoute
  '/category': typeof CategoryRouteRoute
  '/fines': typeof FinesRouteRoute
  '/login': typeof LoginRouteRoute
  '/reader': typeof ReaderRouteRoute
  '/user': typeof UserRouteRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRoute
  '/author': typeof AuthorRouteRoute
  '/book': typeof BookRouteRoute
  '/borrow-records': typeof BorrowRecordsRouteRoute
  '/borrow_records': typeof Borrow_recordsRouteRoute
  '/category': typeof CategoryRouteRoute
  '/fines': typeof FinesRouteRoute
  '/login': typeof LoginRouteRoute
  '/reader': typeof ReaderRouteRoute
  '/user': typeof UserRouteRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRoute
  '/author': typeof AuthorRouteRoute
  '/book': typeof BookRouteRoute
  '/borrow-records': typeof BorrowRecordsRouteRoute
  '/borrow_records': typeof Borrow_recordsRouteRoute
  '/category': typeof CategoryRouteRoute
  '/fines': typeof FinesRouteRoute
  '/login': typeof LoginRouteRoute
  '/reader': typeof ReaderRouteRoute
  '/user': typeof UserRouteRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/author'
    | '/book'
    | '/borrow-records'
    | '/borrow_records'
    | '/category'
    | '/fines'
    | '/login'
    | '/reader'
    | '/user'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/author'
    | '/book'
    | '/borrow-records'
    | '/borrow_records'
    | '/category'
    | '/fines'
    | '/login'
    | '/reader'
    | '/user'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/author'
    | '/book'
    | '/borrow-records'
    | '/borrow_records'
    | '/category'
    | '/fines'
    | '/login'
    | '/reader'
    | '/user'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRoute
  AuthorRouteRoute: typeof AuthorRouteRoute
  BookRouteRoute: typeof BookRouteRoute
  BorrowRecordsRouteRoute: typeof BorrowRecordsRouteRoute
  Borrow_recordsRouteRoute: typeof Borrow_recordsRouteRoute
  CategoryRouteRoute: typeof CategoryRouteRoute
  FinesRouteRoute: typeof FinesRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  ReaderRouteRoute: typeof ReaderRouteRoute
  UserRouteRoute: typeof UserRouteRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader': {
      id: '/reader'
      path: '/reader'
      fullPath: '/reader'
      preLoaderRoute: typeof ReaderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fines': {
      id: '/fines'
      path: '/fines'
      fullPath: '/fines'
      preLoaderRoute: typeof FinesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category': {
      id: '/category'
      path: '/category'
      fullPath: '/category'
      preLoaderRoute: typeof CategoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrow_records': {
      id: '/borrow_records'
      path: '/borrow_records'
      fullPath: '/borrow_records'
      preLoaderRoute: typeof Borrow_recordsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borrow-records': {
      id: '/borrow-records'
      path: '/borrow-records'
      fullPath: '/borrow-records'
      preLoaderRoute: typeof BorrowRecordsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/author': {
      id: '/author'
      path: '/author'
      fullPath: '/author'
      preLoaderRoute: typeof AuthorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRoute,
  AuthorRouteRoute: AuthorRouteRoute,
  BookRouteRoute: BookRouteRoute,
  BorrowRecordsRouteRoute: BorrowRecordsRouteRoute,
  Borrow_recordsRouteRoute: Borrow_recordsRouteRoute,
  CategoryRouteRoute: CategoryRouteRoute,
  FinesRouteRoute: FinesRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  ReaderRouteRoute: ReaderRouteRoute,
  UserRouteRoute: UserRouteRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
